module.exports = [
  {
    date: new Date(),
  },
  {
    date: new Date(new Date().setDate(new Date().getDate()-1)),
  },
  {
    date: new Date(new Date().setDate(new Date().getDate()-2)),
  },
  {
    date: new Date(new Date().setDate(new Date().getDate()-3)),
  },
  {
    date: new Date(new Date().setDate(new Date().getDate()-4)),
  },
  { date: new Date(new Date().setDate(new Date().getDate()-5)), },
{ date: new Date(new Date().setDate(new Date().getDate()-6)), },
{ date: new Date(new Date().setDate(new Date().getDate()-7)), },
{ date: new Date(new Date().setDate(new Date().getDate()-8)), },
{ date: new Date(new Date().setDate(new Date().getDate()-9)), },
{ date: new Date(new Date().setDate(new Date().getDate()-10)), },
{ date: new Date(new Date().setDate(new Date().getDate()-11)), },
{ date: new Date(new Date().setDate(new Date().getDate()-12)), },
{ date: new Date(new Date().setDate(new Date().getDate()-13)), },
{ date: new Date(new Date().setDate(new Date().getDate()-14)), },
{ date: new Date(new Date().setDate(new Date().getDate()-15)), },
{ date: new Date(new Date().setDate(new Date().getDate()-16)), },
{ date: new Date(new Date().setDate(new Date().getDate()-17)), },
{ date: new Date(new Date().setDate(new Date().getDate()-18)), },
{ date: new Date(new Date().setDate(new Date().getDate()-19)), },
{ date: new Date(new Date().setDate(new Date().getDate()-20)), },
{ date: new Date(new Date().setDate(new Date().getDate()-21)), },
{ date: new Date(new Date().setDate(new Date().getDate()-22)), },
{ date: new Date(new Date().setDate(new Date().getDate()-23)), },
{ date: new Date(new Date().setDate(new Date().getDate()-24)), },
{ date: new Date(new Date().setDate(new Date().getDate()-25)), },
{ date: new Date(new Date().setDate(new Date().getDate()-26)), },
{ date: new Date(new Date().setDate(new Date().getDate()-27)), },
{ date: new Date(new Date().setDate(new Date().getDate()-28)), },
{ date: new Date(new Date().setDate(new Date().getDate()-29)), },
{ date: new Date(new Date().setDate(new Date().getDate()-30)), },
{ date: new Date(new Date().setDate(new Date().getDate()-31)), },
{ date: new Date(new Date().setDate(new Date().getDate()-32)), },
{ date: new Date(new Date().setDate(new Date().getDate()-33)), },
{ date: new Date(new Date().setDate(new Date().getDate()-34)), },
{ date: new Date(new Date().setDate(new Date().getDate()-35)), },
{ date: new Date(new Date().setDate(new Date().getDate()-36)), },
{ date: new Date(new Date().setDate(new Date().getDate()-37)), },
{ date: new Date(new Date().setDate(new Date().getDate()-38)), },
{ date: new Date(new Date().setDate(new Date().getDate()-39)), },
{ date: new Date(new Date().setDate(new Date().getDate()-40)), },
{ date: new Date(new Date().setDate(new Date().getDate()-41)), },
{ date: new Date(new Date().setDate(new Date().getDate()-42)), },
{ date: new Date(new Date().setDate(new Date().getDate()-43)), },
{ date: new Date(new Date().setDate(new Date().getDate()-44)), },
{ date: new Date(new Date().setDate(new Date().getDate()-45)), },
{ date: new Date(new Date().setDate(new Date().getDate()-46)), },
{ date: new Date(new Date().setDate(new Date().getDate()-47)), },
{ date: new Date(new Date().setDate(new Date().getDate()-48)), },
{ date: new Date(new Date().setDate(new Date().getDate()-49)), },
{ date: new Date(new Date().setDate(new Date().getDate()-50)), },
{ date: new Date(new Date().setDate(new Date().getDate()-51)), },
{ date: new Date(new Date().setDate(new Date().getDate()-52)), },
{ date: new Date(new Date().setDate(new Date().getDate()-53)), },
{ date: new Date(new Date().setDate(new Date().getDate()-54)), },
{ date: new Date(new Date().setDate(new Date().getDate()-55)), },
{ date: new Date(new Date().setDate(new Date().getDate()-56)), },
{ date: new Date(new Date().setDate(new Date().getDate()-57)), },
{ date: new Date(new Date().setDate(new Date().getDate()-58)), },
{ date: new Date(new Date().setDate(new Date().getDate()-59)), },
{ date: new Date(new Date().setDate(new Date().getDate()-60)), },
];
